
server:
  port: 9527
  servlet:
    context-path: /studytool



info:
  app:
    encoding: @project.build.sourceEncoding@
    version: @project.version@
  java:
    source: @java.version@
    target: @java.version@


authorization:
  name: token
  swagger: true
  path:
    includes: /**
    excludes: /druid/**,/swagger-resources/**,/v2/**